version: "3.7"
services:
  server:
    image: >-
      ghcr.io/matter-js/matterjs-server:1.4.0
    restart: on-failure
    network_mode: host
    security_opt:
      - apparmor:unconfined
    volumes:
      - type: bind
        source: ${APP_DATA_ROOT}
        target: /data/
        read_only: false
        bind:
          create_host_path: false
      - /run/dbus:/run/dbus:ro
    container_name: matter-server_server_1
